import sqlite3
from tkinter import *
import tkinter  as tk
from tkinter import messagebox
root = Tk()
root.title("SET 3")

def insert():
    d1 = e1.get()
    d2 =e2.get()
    d3 = e3.get()
    d4 = e4.get()
    d5 = e5.get()
    d6 = e6.get()
    d7 = e7.get()
    d8 = e8.get()
    d9 = e9.get()
    d10=e10.get()
    d11=e11.get()
    d12=e12.get()
    d13=e13.get()
    d14=e14.get()
    d15 = e15.get()
    d16 = e16.get()
    d17 = e17.get()
    d18 = e18.get()
    d19 = e19.get()
    d20 = e20.get()
    d21 =e21.get()
    d22 = e22.get()
    d23= e23.get()
    d24=e24.get()
    d25=e25.get()
    d26=e26.get()
    d27=e27.get()
    conn = sqlite3.connect('register.db')
    with conn:
        cursor=conn.cursor()
        cursor.execute('CREATE TABLE IF NOT EXISTS Comp (data1 TEXT,data2 TEXT,data3 TEXT,data4 TEXT,data5 TEXT, data6 TEXT,data7 TEXT,data8 TEXT,data9 TEXT,data10 TEXT,data11 TEXT, data12 TEXT, data13 TEXT,data14 TEXT,data15 TEXT,data16 TEXT,data17 TEXT, data18 TEXT, data19 TEXT,data20 TEXT,data21 TEXT,data22 TEXT,data23 TEXT, data24 TEXT, data25 TEXT,data26 TEXT,data27 TEXT)')
        cursor.execute('INSERT INTO Comp (data1, data2, data3, data4, data5, data6, data7 ,data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19, data20, data21, data22, data23, data24, data25, data26, data27) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,))
    conn.commit()
    msg = messagebox.showinfo( "DB Demo","One Row Inserted")
    
def dele():
    conn = sqlite3.connect('register.db')
    with conn:
        cursor=conn.cursor()
        cursor.execute('DELETE FROM Comp')
        msg = messagebox.showinfo( "Delete Record","All Row Deleted") 
        
def disp():
    conn = sqlite3.connect('register.db')
    with conn:
        cursor=conn.cursor()
        my_w = tk.Tk()
        my_w.geometry("400x250") 

        r_set=cursor.execute('''SELECT * from Comp ''');
        i=0 # row value inside the loop 
        for Comp in r_set: 
            for j in range(len(Comp)):
                e = Entry(my_w, width=10, fg='blue') 
                e.grid(row=i, column=j) 
                e.insert(END, Comp[j])
            i=i+1  

titleframe = Frame(root, bg ="gray80")
titleframe.grid(row=0, column=0, columnspan=7, sticky='ew')
titlelabel = Label(titleframe,text="         ",font=("Calibri Bold",15), bg ="gray80")
titlelabel.grid(row=0, column=3)
l651 = Label(root, text="REGISTRATION INFORMATION",font=("Calibri Bold",15),bg="gray80")
l651.grid(row=0,column=0,columnspan=5)
l1 = Label(root,text="Registration Period: (check one)",height=3)
l1.grid(row=1,column=0)
C651 = Checkbutton( text = "One Year", width = 20)
C651.grid(row=1,column=1)
C2 = Checkbutton( text = "Two Years",width = 20)
C2.grid(row=1,column=2)
C3 = Checkbutton( text = "Three Years", width = 20)
C3.grid(row=1,column=3)
l2 = Label(root,text="Registration Type: (check one)")
l2.grid(row=2,column=0)
C4 = Checkbutton( text = "Original",width = 20)
C4.grid(row=2,column=1)
C5 = Checkbutton( text = "Renewal",width = 20)
C5.grid(row=2,column=2)
C6 = Checkbutton( text = "Private",width = 20)
C6.grid(row=2,column=3)
C7 = Checkbutton( text = "Reissue",width = 20)
C7.grid(row=2,column=4)
C8 = Checkbutton( text = "Reissue(Decals Only)",width = 20)
C8.grid(row=3,column=0)
C9 = Checkbutton( text = "Rental Vehicle",width = 20)
C9.grid(row=3,column=1)
C10 = Checkbutton( text = "Transfer License Plate number",width = 25)
C10.grid(row=3,column=2)
e1= Entry()
e1.grid(row=3,column=3)
C9 = Checkbutton( text = "For Hire (Complete for Hire section)",width=30)
C9.grid(row=4,column=0)
C10 = Checkbutton( text = "Ridesharing (Carpool) (Passengers cannot exeed 15 including driver")
C10.grid(row=4,column=2)
e2= Entry()
e2.grid(row=4,column=3)
C9 = Checkbutton( text = "Amatuer Radio operater Call letters-")
C9.grid(row=5,column=0)
e3= Entry()
e3.grid(row=5,column=1)
C11 = Checkbutton( text = "Other",height=3)
C11.grid(row=5,column=3)
e4= Entry()
e4.grid(row=5,column=4)
titleframe = Frame(root, bg ="gray80")
titleframe.grid(row=6, column=0, columnspan=7, sticky='ew')
titlelabel = Label(titleframe,text="         ",font=("Calibri Bold",15), bg ="gray80")
titlelabel.grid(row=6, column=3)
l = Label(root, text="OWNER INFORMATION",font=("Calibri Bold",15),bg="gray80")
l.grid(row=6,column=2)
l = Label(root, text="Owner' full legal name or bussiness name",height=3)
l.grid(row=7,column=0)
e5= Entry()
e5.grid(row=7,column=1)
l = Label(root, text="Telephone number")
l.grid(row=7,column=3)
e6= Entry()
e6.grid(row=7,column=4)
l = Label(root, text="DMV custumer number")
l.grid(row=7,column=5)
e7= Entry()
e7.grid(row=7,column=6)
l = Label(root, text="Co-owner's full legal name or bussiness name")
l.grid(row=8,column=0)
e8= Entry()
e8.grid(row=8,column=1)
l = Label(root, text="Telephone number")
l.grid(row=8,column=3)
e9= Entry()
e9.grid(row=8,column=4)
l = Label(root, text="DMV custumer number")
l.grid(row=8,column=5)
e10= Entry()
e10.grid(row=8,column=6)
l4 = Label(root, text="NOTE:\n" "Owners MUST provide for residence/home/bussiness\n address where requested.")
l4.grid(row=9,column=0)
l4 = Label(root, text="Residence/Bussiness Jurisdiction")
l4.grid(row=9,column=3)
e11= Entry()
e11.grid(row=9,column=4)
l = Label(root, text="Owners' Home/Bussiness Address")
l.grid(row=10,column=0)
e12= Entry()
e12.grid(row=10,column=1)
##l = Label(root, text="City",width=10)
##l.grid(row=10,column=2)
e13= Entry()
e13.grid(row=10,column=2)
l = Label(root, text="State")
l.grid(row=10,column=3)
e14= Entry()
e14.grid(row=10,column=4)
l = Label(root, text="Zip Code")
l.grid(row=10,column=5)
e15= Entry()
e15.grid(row=10,column=6)
l = Label(root, text="Co-Owners' Home/Bussiness Address")
l.grid(row=11,column=0)
e16= Entry()
e16.grid(row=11,column=1)
##l = Label(root, text="City",width=10)
##l.grid(row=10,column=2)
e17= Entry()
e17.grid(row=11,column=2)
l = Label(root, text="State")
l.grid(row=11,column=3)
e18= Entry()
e18.grid(row=11,column=4)
l = Label(root, text="Zip Code")
l.grid(row=11,column=5)
e19= Entry()
e19.grid(row=11,column=6)
l = Label(root, text="Owners' Email Address")
l.grid(row=12,column=0)
e20= Entry()
e20.grid(row=12,column=1)
l = Label(root, text="Co-owners' Email Address")
l.grid(row=12,column=3)
e21= Entry()
e21.grid(row=12,column=4)
tframe = Frame(root, bg ="gray80")
tframe.grid(row=13, column=0, columnspan=7, sticky='ew')
tlabel = Label(tframe,text="         ",font=("Calibri Bold",15), bg ="gray80")
tlabel.grid(row=13, column=3)
l = Label(root, text="ADDITIONAL INFORMATION",font=("Calibri Bold",15),bg="gray80")
l.grid(row=13,column=2)
l = Label(root, text="Location where Vehicle is gaurded")
l.grid(row=14,column=0)
e22= Entry()
e22.grid(row=15,column=0)
l = Label(root, text="IF new location enter date changed")
l.grid(row=14,column=2)
e23= Entry()
e23.grid(row=15,column=2)
l = Label(root, text="Are any of the owners on active milatary duty")
l.grid(row=14,column=4)
C4 = Checkbutton( text = "Yes")
C4.grid(row=15,column=4)
C4 = Checkbutton( text = "No")
C4.grid(row=15,column=5)
l = Label(root, text="If You would like your registration renewals to be sent to an adress other than given")
l.grid(row=16,column=2)
l = Label(root, text="Registartion mailing Address")
l.grid(row=17,column=0)
e24= Entry()
e24.grid(row=17,column=1)
##l = Label(root, text="City",width=10)
##l.grid(row=10,column=2)
e25= Entry()
e25.grid(row=17,column=2)
l = Label(root, text="State")
l.grid(row=17,column=3)
e26= Entry()
e26.grid(row=17,column=4)
l = Label(root, text="Zip Code")
l.grid(row=17,column=5)
e27= Entry()
e27.grid(row=17,column=6)
insert = Button(root, text="Insert",width=20,bg='lightblue',fg='red',command=insert)
insert.grid(row=18,column=2)
insert = Button(root, text="display",width=20,bg='lightblue',fg='red',command=disp)
insert.grid(row=18,column=4)
insert = Button(root, text="Delete",width=20,bg='lightblue',fg='red',command=dele)
insert.grid(row=18,column=1)
root.mainloop()